site_name: '文档'
site_author: 'andy'
site_description: 'rhapsody文档'
site_url: 'https://www.alsoapp.com/'
copyright: Copyright © 2022 andy

# 文档说明:https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/

# 源码地址
# repo_name: 'yidao620c/core-algorithm'
# repo_url: 'https://github.com/yidao620c/core-algorithm'
# edit_uri: 'blob/master/docs/'

theme: 
  name: material
  language: 'zh'  # 配置语言
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  features:
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.indexes
    - navigation.top
    # - toc.integrate

nav:
- 首页: index.md

- 环境部署-单机版:
  - windows部署-1: setup/rhapsody_windows.md
  - centos7部署-2: setup/rhapsody_centos7.md
  # - 容器部署-3: setup/docker_installer.md
  # - docker安装: setup/docker_setup_centos7.md

- 常用通讯点:
  - Web Service Client操作: comm/Web_Service_Client.md

- 常用过滤器:
  - database: filter/database.md
  - JavaScript: filter/JavaScript.md
  - freemarker: filter/freemarker.md
  

- 其他:
  # - 命名规范: other/naming_conventions.md
  - 正则表达式: filter/regexp.md
  - 常见问题: other/FAQ.md
  # - api操作: other/api.md

markdown_extensions:
  - tables # 数据表格
  - admonition  # 提示块
  - footnotes  # 脚注
  - meta  # 定义元数据，通过文章上下文控制，如disqus
  - pymdownx.caret  # 下划线上标
  - pymdownx.tilde  # 删除线下标
  - pymdownx.critic  # 增加删除修改高亮注释，可修饰行内或段落
  - pymdownx.details  # 提示块可折叠
  - pymdownx.inlinehilite  # 行内代码高亮
  - pymdownx.mark  # 文本高亮
  - pymdownx.smartsymbols  # 符号转换
  - pymdownx.superfences  # 代码嵌套在列表里
  - codehilite:    # 代码高亮，显示行号
      guess_lang: false
      linenums: true
  - toc:  # 锚点
      permalink: true
#  - pymdownx.arithmatex  # 数学公式
  - pymdownx.betterem:  # 对加粗和斜体更好的检测
      smart_enable: all
#  - pymdownx.emoji:  # 表情
#      emoji_generator: !!python/name:pymdownx.emoji.to_svg
#  - pymdownx.magiclink  # 自动识别超链接
  - pymdownx.tasklist:  # 复选框checklist
      custom_checkbox: true

# PDF导出插件
plugins:
  - search


extra:
  version:
    default: stable